# Welcome !

> Let's see what we can do together. Let's take a look at some sentiment analysis.

***To detect good sentences from bad we will use some TF-IDF matrices: Term-frequency - Inverse-Document-Frequency***

![mario](https://img.freepik.com/vecteurs-libre/fond-jeu-video-dessine-main_23-2150320542.jpg)

### What is it?
Let's say we have for example: **"I love this cat"** and **"I love this dog"**, **"I hate the movie"**
In this case, we can see that the frequency of love over the first sentence is 1, over the second 1 and finally 0. 
The global frequency is 2.
Let's take a look at: "I", the frequency over all sentences is respectively 1. 
The global fequency of I over the document (3 sentences) is 3.

### Does it mean "I" is more important than "love"?
Nop, you're right, "I" is not more important. To focus on correctness of the frequency over all documents, we have to multiply the TF (term fequency) with the IDF (inverse-document-frequency):

***TF * log(N/df)***

N = 3 (because 3 sentences)
* For "I":
TF = 1 for the first sentence
df = 3 because "I" appears in all 3 documents

**TF-IDF("I") = 0**, therefore, "I" in the first document is not a valuable information.

* For "love":
TF = 1 for the first sentence
df = 2 because "love" appears in 2 / 3 documents

**TF-IDF("love")** = 0.17, therefore "love" is a little valuable in the first sentence.

***PS: this approach will be quite wrong as it will not take into account any context.***


| When you see a MARIO STAR, it means it's your time to shine and to code!


In [1]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

### Below is some bad and good 

We will use those sentences to create two TF-IDF matrices: one good, one bad. 
Later, we will compare every sentence we want with the two matrices and check which of the two has the closest cosine similarity (distance) in terms of TF-IDF value with the sentence we want to predict the sentiment.
If you don't understand yet, no worries keep up!

In [2]:
bad_sentences = [
    ['I', 'hate', 'this'],
    ['I', 'don\'t', 'like', 'it'],
    ['I', 'hate', 'that'],
    ['What', 'a', 'disaster'],
    ['Not', 'good'],
    ['It', 'is', 'bad'],
    ['I', 'am', 'not', 'happy'],
    ['I', 'am', 'unhappy'],
    ['I', 'am', 'sad'],
    ['I', 'am', 'mad'],
    ['I', 'am', 'angry'],
    ['I', 'am', 'not', 'glad'],
    ['I', 'am', 'not', 'pleased'],
    ['I', 'am', 'not', 'satisfied'],
    ['I', 'am', 'not', 'content'],
    ['I', 'am', 'not', 'cheerful'],
    ['I', 'am', 'not', 'delighted'],
    ['I', 'am', 'not', 'joyful'],
    ['I', 'am', 'not', 'joyous'],
    ['I', 'am', 'not', 'jubilant'],
    ['I', 'am', 'not', 'ecstatic'],
    ['I', 'am', 'not', 'elated'],
    ['I', 'am', 'not', 'overjoyed'],
    ['I', 'am', 'not', 'thrilled'],
    ['I', 'am', 'not', 'excited'],
    ['I', 'am', 'not', 'exhilarated'],
    ['I', 'am', 'not', 'euphoric'],
    ['I', 'am', 'not', 'blissful'],
    ['I', 'am', 'not', 'cheery'],
    ['I', 'am', 'not', 'chipper'],
    ['I', 'am', 'not', 'contented'],
    ['I', 'am', 'not', 'enjoying'],
    ['I', 'am', 'not', 'glad'],
    ['I', 'am', 'not', 'gratified'],
    ['I', 'am', 'not', 'gratifying'],
    ['I', 'am', 'not', 'happy'],
    ['I', 'am', 'not', 'joyous'],
    ['I', 'am', 'not', 'jubilant'],
    ['I', 'am', 'not', 'pleased'],
    ['I', 'am', 'not', 'pleasing'],
    ['I', 'am', 'not', 'satisfied']
]

good_sentences = [
    ['I', 'love', 'this'],
    ['I', 'like', 'it'],
    ['I', 'love', 'it'],
    ['What', 'a', 'wonderful', 'day'],
    ['Good'],
    ['It', 'is', 'good'],
    ['I', 'am', 'happy'],
    ['I', 'am', 'glad'],
    ['I', 'am', 'pleased'],
    ['I', 'am', 'satisfied'],
    ['I', 'am', 'content'],
    ['I', 'am', 'cheerful'],
    ['I', 'am', 'delighted'],
    ['I', 'am', 'joyful'],
    ['I', 'am', 'joyous'],
    ['I', 'am', 'jubilant'],
    ['I', 'am', 'ecstatic'],
    ['I', 'am', 'elated'],
    ['I', 'am', 'overjoyed'],
    ['I', 'am', 'thrilled'],
    ['I', 'am', 'excited'],
    ['I', 'am', 'exhilarated'],
    ['I', 'love', 'that', 'a', 'lot'],
    ['I', 'am', 'euphoric'],
    ['I', 'am', 'pleased'],
    ['I', 'am', 'pleasing'],
    ['I', 'am', 'satisfied']

]

**Time to code!** <img src="https://mario.wiki.gallery/images/thumb/f/f5/StarMK8.png/1200px-StarMK8.png" width="200"> **Time to code!**

### 1. Term Frequency
As we said earlier, we will first calculate the term frequency of each word in each sentence.

->TIPS:
- Create an empty dictionary
- Loop over each sentence
- Loop over each word in the sentence
- If the word is already in the dictionary, add 1 to the value
- If the word is not in the dictionary, add the word as a key and set the value to 1

In [3]:
def term_frequency(tokenized_sentences):
    scrypt_tf = {}
    for tokenized_sentence in tokenized_sentences:
        for word in tokenized_sentence:
            if word in scrypt_tf:
                scrypt_tf[word] += 1
            else:
                scrypt_tf[word] = 1
    return scrypt_tf

In [4]:
tf_bad = term_frequency(bad_sentences)
tf_good = term_frequency(good_sentences)

In [5]:
global_shape = len(tf_bad) + len(tf_good)

### 2. TF Matrix
Now that we have the term frequency of each word, we will create a matrix with the shape of the number of sentences and the number of words in the dictionary.

->TIPS:
- Create an empty matrix (list of lists)
- Loop over each sentence
- Create an empty vector (list) of the size: global_shape (this is because we are going to create two TF-IDF matrices: one for good sentences and one for bad sentences. The global_shape will be the same for both matrices)
- Loop over each word in the sentence
- If the word is in the dictionary, add the number of times the word appears in the sentence to the vector
- If the word is not in the dictionary, add 0 to the vector
- Add the vector to the matrix
- Return the matrix

In [6]:
def tf_matrix(tokenized_sentences, tf):
    tf_matrix = []
    for tokenized_sentence in tokenized_sentences:
        tf_vector = [0]*global_shape
        for word in tokenized_sentence:
            if word in tf:
                tf_vector[list(tf.keys()).index(word)] = tokenized_sentence.count(word)
        tf_matrix.append(tf_vector)
    print(
        "Shape of TF Matrix : \n",
        np.array(tf_matrix).shape
    )
    print(
        "TF Matrix : \n",
        np.array(tf_matrix)
    )
    return tf_matrix

In [7]:
tf_matrix_bad = tf_matrix(bad_sentences, tf_bad)
tf_matrix_good = tf_matrix(good_sentences, tf_good)

Shape of TF Matrix : 
 (41, 80)
TF Matrix : 
 [[1 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
Shape of TF Matrix : 
 (27, 80)
TF Matrix : 
 [[1 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


### 3. IDF Matrix
Now that we have the TF matrix, we will create the IDF matrix.

->TIPS:
- Create an empty vector (list)
- Loop over each word in the dictionary
- Create a counter
- Loop over each sentence
- If the word is in the sentence, add 1 to the counter
- Add the log of the number of sentences divided by the counter + 1 to the vector
- Return the vector

In [8]:
def idf_matrix(tf_matrix):
    idf_matrix = []
    for i in range(len(tf_matrix[0])):
        count = 0
        for j in range(len(tf_matrix)):
            if tf_matrix[j][i] != 0:
                count += 1
        idf_matrix.append(np.log((len(tf_matrix)) / (count + 1)))
    print(
        "Shape of IDF Matrix : \n",
        np.array(idf_matrix).shape
    )
    print(
        "IDF Matrix : \n",
        np.array(idf_matrix)
    )
    return idf_matrix

In [9]:
idf_matrix_bad = idf_matrix(tf_matrix_bad)
idf_matrix_good = idf_matrix(tf_matrix_good)

Shape of IDF Matrix : 
 (80,)
IDF Matrix : 
 [0.05001042 2.61495978 3.02042489 3.02042489 3.02042489 3.02042489
 3.02042489 3.02042489 3.02042489 3.02042489 3.02042489 3.02042489
 3.02042489 3.02042489 3.02042489 0.13005313 0.24783616 2.61495978
 3.02042489 3.02042489 3.02042489 3.02042489 2.61495978 2.61495978
 2.61495978 3.02042489 3.02042489 3.02042489 3.02042489 2.61495978
 2.61495978 3.02042489 3.02042489 3.02042489 3.02042489 3.02042489
 3.02042489 3.02042489 3.02042489 3.02042489 3.02042489 3.02042489
 3.02042489 3.02042489 3.02042489 3.02042489 3.71357207 3.71357207
 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207
 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207
 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207
 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207
 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207 3.71357207
 3.71357207 3.71357207]
Shape of IDF Matrix : 
 (80,)
IDF Matrix : 
 [0.07696104 1.9

### 4. TF-IDF Matrix
Now that we have the TF matrix and the IDF matrix, we will create the TF-IDF matrix.

->TIPS:
- Create an empty matrix (list of lists)
- Loop over the TF matrix
- Create an empty vector (list) of the size: global_shape (this is because we are going to create two TF-IDF matrices: one for good sentences and one for bad sentences. The global_shape will be the same for both matrices)
- Loop over each word in the sentence
- Multiply the TF value with the IDF value
- Add the value to the vector
- Add the vector to the matrix
- Return the matrix

In [10]:
def tf_idf_matrix(tf_matrix, idf_matrix):
    tf_idf_matrix = []
    for i in range(len(tf_matrix)):
        tf_idf_vector = []
        for j in range(len(tf_matrix[0])):
            tf_idf_vector.append(tf_matrix[i][j] * idf_matrix[j])
        tf_idf_matrix.append(tf_idf_vector)
    print(
        "Shape of TF-IDF Matrix : \n",
        np.array(tf_idf_matrix).shape
    )
    print(
        "TF-IDF Matrix : \n",
        np.array(tf_idf_matrix)
    )
    return tf_idf_matrix

In [11]:
tf_idf_matrix_bad = tf_idf_matrix(tf_matrix_bad, idf_matrix_bad)
tf_idf_matrix_good = tf_idf_matrix(tf_matrix_good, idf_matrix_good)

Shape of TF-IDF Matrix : 
 (41, 80)
TF-IDF Matrix : 
 [[0.05001042 2.61495978 3.02042489 ... 0.         0.         0.        ]
 [0.05001042 0.         0.         ... 0.         0.         0.        ]
 [0.05001042 2.61495978 0.         ... 0.         0.         0.        ]
 ...
 [0.05001042 0.         0.         ... 0.         0.         0.        ]
 [0.05001042 0.         0.         ... 0.         0.         0.        ]
 [0.05001042 0.         0.         ... 0.         0.         0.        ]]
Shape of TF-IDF Matrix : 
 (27, 80)
TF-IDF Matrix : 
 [[0.07696104 1.9095425  2.60268969 ... 0.         0.         0.        ]
 [0.07696104 0.         0.         ... 0.         0.         0.        ]
 [0.07696104 1.9095425  0.         ... 0.         0.         0.        ]
 ...
 [0.07696104 0.         0.         ... 0.         0.         0.        ]
 [0.07696104 0.         0.         ... 0.         0.         0.        ]
 [0.07696104 0.         0.         ... 0.         0.         0.        ]]


### 5. Check sentiment
Now that we have the two TF-IDF matrices, we can check the sentiment of any sentence we want.
To check the sentiment, we will calculate the cosine similarity between the sentence we want to check and the two TF-IDF matrices.
The TF-IDF matrix with the highest cosine similarity will be the one with the closest distance to the sentence we want to check.

For example, for the sentence "I love this cat", the cosine similarity with the good TF-IDF matrix could be 0.5 and the cosine similarity with the bad TF-IDF matrix could be 0.2.
In this case, the sentence "I love this cat" will be considered as a good sentence.

->TIPS:
- Create a function that takes a query as an input (a sentence)
- Create an empty vector (list) of the size: global_shape (this is because we are going to create two TF-IDF matrices: one for good sentences and one for bad sentences. The global_shape will be the same for both matrices)
- Combine all words from both tf_bad and tf_good as a set: **all_words = set(list(tf_bad.keys()) + list(tf_good.keys()))**
- Loop over each word in the set
- If the word is in the query:
    - If the word is in tf_bad:
        - Add the TF-IDF value to the vector with the index of the word in tf_bad as index and the idf_matrix_bad value as value
    - If the word is in tf_good:
        - Add the TF-IDF value to the vector with the index of the word in tf_good as index and the idf_matrix_good value as value
- Calculate the cosine similarity between the query vector and the good TF-IDF matrix: **cosine_similarity([query_vector], tf_idf_matrix_good)[0][0]**
- Calculate the cosine similarity between the query vector and the bad TF-IDF matrix: **cosine_similarity([query_vector], tf_idf_matrix_bad)[0][0]**
- If the cosine similarity with the good TF-IDF matrix is higher than the cosine similarity with the bad TF-IDF matrix:
    - Print the query with a smiley (or whatever :p)
    - Else: print the query with a sad smiley (or whatever :p)

In [18]:
good_query = "WOW, I am so happy to meet you!"
bad_query = "I hate it a lot!"

In [19]:
def check_sentiment(query):
    query_to_array = query.split()
    # convert the query to a tf-idf vector
    query_tf_idf_vector = [0]*global_shape
    all_words = set(list(tf_bad.keys()) + list(tf_good.keys()))
    for word in all_words:
        if word in query_to_array:
            if word in tf_bad:
                query_tf_idf_vector[list(tf_bad.keys()).index(word)] = query_to_array.count(word) * idf_matrix_bad[list(tf_bad.keys()).index(word)]
            elif word in tf_good:
                query_tf_idf_vector[list(tf_good.keys()).index(word)] = query_to_array.count(word) * idf_matrix_good[list(tf_good.keys()).index(word)]

    # calculate cosine similarity between query vector and good and bad vectors
    cosine_similarities_with_good = cosine_similarity([query_tf_idf_vector], tf_idf_matrix_good)[0][0]
    cosine_similarities_with_bad = cosine_similarity([query_tf_idf_vector], tf_idf_matrix_bad)[0][0]

    if cosine_similarities_with_good >= cosine_similarities_with_bad:
        print(f"{query} => :) UwU")
    else:
        print(f"{query} => :( OoO")

In [20]:
check_sentiment(good_query)
check_sentiment(bad_query)

WOW, I am so happy to meet you! => :) UwU
I hate it a lot! => :( OoO
